// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServidorEmpleados.Models;

public partial class Departamento
{
    public int IdDepartamento { get; set; }

    public string CodigoDepartamento { get; set; }

    public string NombreDepartamento { get; set; }

    public bool Activo { get; set; }

    public virtual ICollection<Puesto> Puestos { get; set; } = new List<Puesto>();
}