// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServidorEmpleados.Models;

public partial class AsignacionPuesto
{
    public int IdAsignacion { get; set; }

    public int IdEmpleado { get; set; }

    public int IdPuesto { get; set; }

    public decimal Salario { get; set; }

    public DateOnly FechaInicio { get; set; }

    public DateOnly? FechaFin { get; set; }

    public string Estado { get; set; }

    public string Observaciones { get; set; }

    public virtual Empleado IdEmpleadoNavigation { get; set; }

    public virtual Puesto IdPuestoNavigation { get; set; }
}