// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServidorEmpleados.Models;

public partial class Empleado
{
    public int IdEmpleado { get; set; }

    public string CodigoEmpleado { get; set; }

    public string FotoRuta { get; set; }

    public string PrimerNombre { get; set; }

    public string SegundoNombre { get; set; }

    public string PrimerApellido { get; set; }

    public string SegundoApellido { get; set; }

    public DateOnly FechaNacimiento { get; set; }

    public DateOnly FechaContratacion { get; set; }

    public string Direccion { get; set; }

    public string Telefono { get; set; }

    public string Email { get; set; }

    public string Estado { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public virtual ICollection<AsignacionPuesto> AsignacionPuestos { get; set; } = new List<AsignacionPuesto>();
}