// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServidorEmpleados.Models;

public partial class Puesto
{
    public int IdPuesto { get; set; }

    public string CodigoPuesto { get; set; }

    public string NombrePuesto { get; set; }

    public string DescripcionPuesto { get; set; }

    public int IdDepartamento { get; set; }

    public bool Activo { get; set; }

    public virtual ICollection<AsignacionPuesto> AsignacionPuestos { get; set; } = new List<AsignacionPuesto>();

    public virtual Departamento IdDepartamentoNavigation { get; set; }
}